## First, the list of datasets should be created.

In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("db/archive")

files = []
for f in DATA_DIR.rglob("*"):
    if f.is_file():
        files.append({
            "path": str(f),
            "name": f.name,
            "suffix": f.suffix,
            "size_mb": round(f.stat().st_size / 1024**2, 2)
        })

inventory = pd.DataFrame(files)
inventory.sort_values("path").head(50)

,path,name,suffix,size_mb
0,db/archive/ACS_variable_descriptions.csv,ACS_variable_descriptions.csv,.csv,0.03
406,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_B15003_metadata.csv,.csv,0.00
407,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_B15003_with_ann.csv,.csv,0.05
412,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1501_metadata.csv,.csv,0.08
413,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1501_with_ann.csv,.csv,0.67
400,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S2301_metadata.csv,.csv,0.03
401,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S2301_with_ann.csv,.csv,0.28
409,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1903_metadata.csv,.csv,0.01
408,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1903_with_ann.csv,.csv,0.13
414,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S2502_metadata.csv,.csv,0.02
415,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S2502_with_ann.csv,.csv,0.17
404,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1701_metadata.csv,.csv,0.04
405,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_S1701_with_ann.csv,.csv,0.33
402,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_DP05_metadata.csv,.csv,0.03
403,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_DP05_with_ann.csv,.csv,0.29
410,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_DP05_metadata.csv,.csv,0.03
411,db/archive/Dept_11-00091/11-00091_ACS_data/11-...,ACS_15_5YR_DP05_with_ann.csv,.csv,0.29
7,db/archive/Dept_11-00091/11-00091_Field-Interv...,11-00091_Field-Interviews_2011-2015.csv,.csv,37.45
396,db/archive/Dept_11-00091/11-00091_Shapefiles/b...,boston_police_districts_f55.cst,.cst,0.00
399,db/archive/Dept_11-00091/11-00091_Shapefiles/b...,boston_police_districts_f55.dbf,.dbf,0.01
395,db/archive/Dept_11-00091/11-00091_Shapefiles/b...,boston_police_districts_f55.prj,.prj,0.00
397,db/archive/Dept_11-00091/11-00091_Shapefiles/b...,boston_police_districts_f55.shp,.shp,0.53
398,db/archive/Dept_11-00091/11-00091_Shapefiles/b...,boston_police_districts_f55.shx,.shx,0.00
463,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_B15003_metadata.csv,.csv,0.00
464,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_B15003_with_ann.csv,.csv,0.05
459,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1501_metadata.csv,.csv,0.08
460,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1501_with_ann.csv,.csv,0.73
465,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S2301_metadata.csv,.csv,0.03
466,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S2301_with_ann.csv,.csv,0.31
462,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1903_metadata.csv,.csv,0.01
461,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1903_with_ann.csv,.csv,0.14
469,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S2502_metadata.csv,.csv,0.02
470,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S2502_with_ann.csv,.csv,0.18
471,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1701_metadata.csv,.csv,0.04
472,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_S1701_with_ann.csv,.csv,0.36
467,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_DP05_metadata.csv,.csv,0.03
468,db/archive/Dept_23-00089/23-00089_ACS_data/23-...,ACS_15_5YR_DP05_with_ann.csv,.csv,0.32
458,db/archive/Dept_23-00089/23-00089_Shapefiles/I...,Indianapolis_Police_Zones.cpg,.cpg,0.00
456,db/archive/Dept_23-00089/23-00089_Shapefiles/I...,Indianapolis_Police_Zones.dbf,.dbf,0.02
455,db/archive/Dept_23-00089/23-00089_Shapefiles/I...,Indianapolis_Police_Zones.prj,.prj,0.00
454,db/archive/Dept_23-00089/23-00089_Shapefiles/I...,Indianapolis_Police_Zones.shp,.shp,0.26
457,db/archive/Dept_23-00089/23-00089_Shapefiles/I...,Indianapolis_Police_Zones.shx,.shx,0.00
10,db/archive/Dept_23-00089/23-00089_UOF-P.csv,23-00089_UOF-P.csv,.csv,2.96
424,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_B15003_metadata.csv,.csv,0.00
425,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_B15003_with_ann.csv,.csv,0.07
432,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_S1501_metadata.csv,.csv,0.08
433,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_S1501_with_ann.csv,.csv,0.95
430,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_S2301_metadata.csv,.csv,0.03
431,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_S2301_with_ann.csv,.csv,0.40
427,db/archive/Dept_24-00013/24-00013_ACS_data/24-...,ACS_15_5YR_S1903_metadata.csv,.csv,0.01

## Now, the list of only .csv files

In [2]:
csv_files = inventory[inventory["suffix"].str.lower() == ".csv"]
csv_files[["path", "name", "size_mb"]]

,path,name,size_mb
0,db/archive/ACS_variable_descriptions.csv,ACS_variable_descriptions.csv,0.03
1,db/archive/Dept_35-00103/35-00103_UOF-OIS-P_pr...,35-00103_UOF-OIS-P_prepped.csv,0.01
2,db/archive/Dept_49-00081/49-00081_Incident-Rep...,49-00081_Incident-Reports_2012_to_May_2015.csv,52.16
3,db/archive/Dept_37-00049/37-00049_UOF-P_2016_p...,37-00049_UOF-P_2016_prepped.csv,0.87
4,db/archive/Dept_49-00035/49-00035_Incidents_20...,49-00035_Incidents_2016.csv,0.92
...,...,...,...
527,db/archive/Dept_37-00027/37-00027_ACS_data/37-...,ACS_15_5YR_S1903_metadata.csv,0.01
528,db/archive/Dept_37-00027/37-00027_ACS_data/37-...,ACS_15_5YR_S2301_metadata.csv,0.03
529,db/archive/Dept_37-00027/37-00027_ACS_data/37-...,ACS_15_5YR_S2301_with_ann.csv,0.30
530,db/archive/Dept_37-00027/37-00027_ACS_data/37-...,ACS_15_5YR_S1501_metadata.csv,0.08
531,db/archive/Dept_37-00027/37-00027_ACS_data/37-...,ACS_15_5YR_S1501_with_ann.csv,0.73

## Files about policing incident records

In [3]:
keywords = ["uof", "force", "incident", "police", "stop", "prepped"]

candidate_files = csv_files[
    csv_files["name"].str.lower().apply(
        lambda x: any(k in x for k in keywords)
    )
]

candidate_files[["path", "name", "size_mb"]]

,path,name,size_mb
1,db/archive/Dept_35-00103/35-00103_UOF-OIS-P_pr...,35-00103_UOF-OIS-P_prepped.csv,0.01
2,db/archive/Dept_49-00081/49-00081_Incident-Rep...,49-00081_Incident-Reports_2012_to_May_2015.csv,52.16
3,db/archive/Dept_37-00049/37-00049_UOF-P_2016_p...,37-00049_UOF-P_2016_prepped.csv,0.87
4,db/archive/Dept_49-00035/49-00035_Incidents_20...,49-00035_Incidents_2016.csv,0.92
5,db/archive/Dept_35-00016/35-00016_UOF-OIS-P.csv,35-00016_UOF-OIS-P.csv,0.01
8,db/archive/Dept_24-00013/24-00013_UOF_2008-201...,24-00013_UOF_2008-2017_prepped.csv,2.84
10,db/archive/Dept_23-00089/23-00089_UOF-P.csv,23-00089_UOF-P.csv,2.96
11,db/archive/Dept_49-00009/49-00009_UOF.csv,49-00009_UOF.csv,0.80
12,db/archive/Dept_49-00009/49-0009_UOF.csv,49-0009_UOF.csv,0.80
13,db/archive/Dept_24-00098/24-00098_Vehicle-Stop...,24-00098_Vehicle-Stops-data.csv,54.74
14,db/archive/Dept_37-00027/37-00027_UOF-P_2014-2...,37-00027_UOF-P_2014-2016_prepped.csv,3.41
130,db/archive/cpe-data/Dept_35-00103/35-00103_UOF...,35-00103_UOF-OIS-P_prepped.csv,0.01
131,db/archive/cpe-data/Dept_49-00081/49-00081_Inc...,49-00081_Incident-Reports_2012_to_May_2015.csv,52.16
132,db/archive/cpe-data/Dept_37-00049/37-00049_UOF...,37-00049_UOF-P_2016_prepped.csv,0.87
133,db/archive/cpe-data/Dept_49-00035/49-00035_Inc...,49-00035_Incidents_2016.csv,0.92
134,db/archive/cpe-data/Dept_35-00016/35-00016_UOF...,35-00016_UOF-OIS-P.csv,0.01
136,db/archive/cpe-data/Dept_24-00013/24-00013_UOF...,24-00013_UOF_2008-2017_prepped.csv,2.84
138,db/archive/cpe-data/Dept_23-00089/23-00089_UOF...,23-00089_UOF-P.csv,2.96
139,db/archive/cpe-data/Dept_49-00009/49-00009_UOF...,49-00009_UOF.csv,0.80
140,db/archive/cpe-data/Dept_49-00009/49-0009_UOF.csv,49-0009_UOF.csv,0.80
141,db/archive/cpe-data/Dept_24-00098/24-00098_Veh...,24-00098_Vehicle-Stops-data.csv,54.74
142,db/archive/cpe-data/Dept_37-00027/37-00027_UOF...,37-00027_UOF-P_2014-2016_prepped.csv,3.41

## The dataset 49-00081_Incident-Reports_2012_to_May_2015.csv was chosen as it was one of the biggest

In [5]:
main_file = "db/archive/cpe-data/Dept_49-00081/49-00081_Incident-Reports_2012_to_May_2015.csv"
df = pd.read_csv(main_file)

df.shape, df.head()

/tmp/ipykernel_19519/2565197255.py:2: DtypeWarning: Columns (0: INCIDENT_UNIQUE_IDENTIFIER, 1: LOCATION_LONGITUDE, 2: LOCATION_LATITUDE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(main_file)

((394236, 11),
   INCIDENT_UNIQUE_IDENTIFIER INCIDENT_REASON  \
 0                 IncidntNum        Category
 1                  120000790  SUSPICIOUS OCC
 2                  120004770    NON-CRIMINAL
 3                  120000712         ASSAULT
 4                  120064611    NON-CRIMINAL

                      INCIDENT_REASON_DESCRIPTION INCIDENT_DAY INCIDENT_DATE  \
 0                                       Descript    DayOfWeek          Date
 1                        INVESTIGATIVE DETENTION       Sunday        1/1/12
 2                                  LOST PROPERTY       Sunday        1/1/12
 3  BATTERY, FORMER SPOUSE OR DATING RELATIONSHIP       Sunday        1/1/12
 4                                  LOST PROPERTY       Sunday        1/1/12

   INCIDENT_TIME LOCATION_DISTRICT     DISPOSITION  \
 0          Time        PdDistrict      Resolution
 1          4:50          SOUTHERN            NONE
 2          1:25           MISSION            NONE
 3          3:35         INGLESIDE  ARREST, BOOKED
 4         22:00         INGLESIDE            NONE

   LOCATION_FULL_STREET_ADDRESS_OR_INTERSECTION LOCATION_LONGITUDE  \
 0                                      Address                  X
 1                            0 Block of 7TH ST       -122.4122725
 2                     2800 Block of MISSION ST        -122.418434
 3                    2000 Block of SAN JOSE AV       -122.4439879
 4                       300 Block of HEARST AV       -122.4454574

   LOCATION_LATITUDE
 0                 Y
 1       37.78020391
 2       37.75141993
 3       37.72397891
 4       37.73064873  )